In [2]:
import pandas as pd
import numpy as np

In [4]:
path='D:/sentiment_analysis/dataset.csv'
df=pd.read_csv(path)
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.dropna()

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [7]:
df.duplicated().sum()

418

In [8]:
df=df.drop_duplicates()

In [9]:
df.duplicated().sum()

0

In [10]:
df['sentiment'].value_counts()

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [11]:
import re
df=df.copy()
def html_tag_removal(text):
    return re.sub(r'<.*?>','',text)
df['review']=df['review'].apply(html_tag_removal)

In [12]:
def url_removal(text):
    return re.sub(r'http\S+|www\S+','',text)
df['review']=df['review'].apply(url_removal)

In [13]:
import string 
def punctuation_removal(text):
    return text.translate(str.maketrans('','',string.punctuation))
df['review']=df['review'].apply(punctuation_removal)

In [14]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production The filming tech...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically theres a family where a little boy J...  negative
4  Petter Matteis Love in the Time of Money is a ...  positive

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['sentiment']=encoder.fit_transform(df['sentiment'])

In [17]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production The filming tech...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically theres a family where a little boy J...          0
4      Petter Matteis Love in the Time of Money is a ...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot bad dialogue bad acting idiotic direc...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  Im going to have to disagree with the previous...          0
49999  No one expects the Star Trek movies to be high...          0

[49582 rows x 2 columns]

In [18]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(num_words=5000,oov_token='Nothing')
tokenizer.fit_on_texts(df['review'])

WARNING:tensorflow:From c:\Users\mdfaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [20]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production The filming tech...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically theres a family where a little boy J...          0
4      Petter Matteis Love in the Time of Money is a ...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot bad dialogue bad acting idiotic direc...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  Im going to have to disagree with the previous...          0
49999  No one expects the Star Trek movies to be high...          0

[49582 rows x 2 columns]

In [21]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'of': 5,
 'to': 6,
 'is': 7,
 'in': 8,
 'it': 9,
 'this': 10,
 'i': 11,
 'that': 12,
 'was': 13,
 'as': 14,
 'with': 15,
 'for': 16,
 'movie': 17,
 'but': 18,
 'film': 19,
 'on': 20,
 'not': 21,
 'you': 22,
 'are': 23,
 'his': 24,
 'have': 25,
 'be': 26,
 'he': 27,
 'one': 28,
 'its': 29,
 'at': 30,
 'all': 31,
 'by': 32,
 'an': 33,
 'they': 34,
 'who': 35,
 'from': 36,
 'like': 37,
 'so': 38,
 'or': 39,
 'just': 40,
 'her': 41,
 'about': 42,
 'has': 43,
 'out': 44,
 'if': 45,
 'some': 46,
 'what': 47,
 'there': 48,
 'good': 49,
 'more': 50,
 'very': 51,
 'when': 52,
 'even': 53,
 'up': 54,
 'no': 55,
 'my': 56,
 'would': 57,
 'she': 58,
 'time': 59,
 'which': 60,
 'only': 61,
 'really': 62,
 'their': 63,
 'see': 64,
 'were': 65,
 'story': 66,
 'had': 67,
 'can': 68,
 'me': 69,
 'than': 70,
 'much': 71,
 'we': 72,
 'well': 73,
 'been': 74,
 'get': 75,
 'will': 76,
 'other': 77,
 'into': 78,
 'great': 79,
 'do': 80,
 'bad': 81,
 'because': 82,
 'also': 83,
 'people': 84,
 'how': 85,
 'most': 86,
 'him': 87,
 'first': 88,
 'dont': 89,
 'movies': 90,
 'made': 91,
 'them': 92,
 'then': 93,
 'films': 94,
 'make': 95,
 'could': 96,
 'way': 97,
 'any': 98,
 'too': 99,
 'characters': 100,
 'after': 101,
 'think': 102,
 'watch': 103,
 'many': 104,
 'seen': 105,
 'being': 106,
 'character': 107,
 'two': 108,
 'never': 109,
 'love': 110,
 'acting': 111,
 'where': 112,
 'did': 113,
 'best': 114,
 'plot': 115,
 'little': 116,
 'know': 117,
 'show': 118,
 'life': 119,
 'ever': 120,
 'does': 121,
 'your': 122,
 'better': 123,
 'off': 124,
 'say': 125,
 'over': 126,
 'still': 127,
 'these': 128,
 'scene': 129,
 'end': 130,
 'man': 131,
 'scenes': 132,
 'why': 133,
 'here': 134,
 'such': 135,
 'while': 136,
 'something': 137,
 'go': 138,
 'should': 139,
 'through': 140,
 'those': 141,
 'back': 142,
 'real': 143,
 'im': 144,
 'watching': 145,
 'thing': 146,
 'doesnt': 147,
 'didnt': 148,
 'actors': 149,
 'years': 150,
 'now': 151,
 'actually': 152,
 'though': 153,
 'makes': 154,
 'funny': 155,
 'before': 156,
 'another': 157,
 'find': 158,
 'nothing': 159,
 'look': 160,
 'going': 161,
 'work': 162,
 'same': 163,
 'lot': 164,
 'new': 165,
 'few': 166,
 'every': 167,
 'old': 168,
 'us': 169,
 'part': 170,
 'cant': 171,
 'again': 172,
 'director': 173,
 'want': 174,
 'quite': 175,
 'thats': 176,
 'things': 177,
 'pretty': 178,
 'cast': 179,
 'seems': 180,
 'around': 181,
 'young': 182,
 'got': 183,
 'down': 184,
 'take': 185,
 'fact': 186,
 'world': 187,
 'enough': 188,
 'big': 189,
 'both': 190,
 'horror': 191,
 'thought': 192,
 'give': 193,
 'may': 194,
 'between': 195,
 'own': 196,
 'ive': 197,
 'however': 198,
 'without': 199,
 'long': 200,
 'saw': 201,
 'isnt': 202,
 'gets': 203,
 'always': 204,
 'right': 205,
 'music': 206,
 'almost': 207,
 'must': 208,
 'original': 209,
 'come': 210,
 'comedy': 211,
 'times': 212,
 'whole': 213,
 'role': 214,
 'least': 215,
 'series': 216,
 'interesting': 217,
 'guy': 218,
 'action': 219,
 'point': 220,
 'bit': 221,
 'done': 222,
 'theres': 223,
 'might': 224,
 'far': 225,
 'am': 226,
 'hes': 227,
 'minutes': 228,
 'script': 229,
 'feel': 230,
 'anything': 231,
 'last': 232,
 'since': 233,
 'probably': 234,
 'family': 235,
 'kind': 236,
 'performance': 237,
 'tv': 238,
 'away': 239,
 'rather': 240,
 'yet': 241,
 'worst': 242,
 'each': 243,
 'found': 244,
 'fun': 245,
 'anyone': 246,
 'sure': 247,
 'played': 248,
 'girl': 249,
 'making': 250,
 'our': 251,
 'believe': 252,
 'woman': 253,
 'trying': 254,
 'shows': 255,
 'especially': 256,
 'course': 257,
 'having': 258,
 'comes': 259,
 'hard': 260,
 'goes': 261,
 'day': 262,
 'put': 263,
 'everything': 264,
 'although': 265,
 'different': 266,
 'worth': 267,
 'looking': 268,
 'dvd': 269,
 'main': 270,
 'ending': 271,
 'place': 272,
 'looks': 273,
 'wasnt': 274,
 'watched': 275,
 'maybe': 276,
 'book': 277,
 'sense': 278,
 'reason': 279,
 'once': 280,
 'screen': 281,
 'three': 282,
 'set': 283,
 'effects': 284,
 'plays': 285,
 'someone': 286,
 'true': 287,
 'play': 288,
 'job': 289,
 'money': 290,
 'during': 291,
 'actor': 292,
 'together': 293,
 'said': 294,
 'takes': 295,
 'seem': 296,
 '10': 297,
 'american': 298,
 'everyone': 299,
 'instead': 300,
 '2': 301,
 'special': 302,
 'beautiful': 303,
 'seeing': 304,
 'later': 305,
 'left': 306,
 'audience': 307,
 'himself': 308,
 'war': 309,
 'version': 310,
 'excellent': 311,
 'john': 312,
 'idea': 313,
 'night': 314,
 'shot': 315,
 'black': 316,
 'high': 317,
 'simply': 318,
 'youre': 319,
 'fan': 320,
 'completely': 321,
 'used': 322,
 'house': 323,
 'nice': 324,
 'read': 325,
 'wife': 326,
 'else': 327,
 'poor': 328,
 'death': 329,
 'kids': 330,
 'short': 331,
 'friends': 332,
 'help': 333,
 'along': 334,
 'men': 335,
 'second': 336,
 'mind': 337,
 'star': 338,
 'use': 339,
 'need': 340,
 'home': 341,
 'less': 342,
 'given': 343,
 'try': 344,
 'enjoy': 345,
 'half': 346,
 'year': 347,
 'boring': 348,
 'until': 349,
 'truly': 350,
 'classic': 351,
 'rest': 352,
 'either': 353,
 'recommend': 354,
 'performances': 355,
 'couple': 356,
 'production': 357,
 'dead': 358,
 'wrong': 359,
 'line': 360,
 'father': 361,
 'start': 362,
 'hollywood': 363,
 'tell': 364,
 'stupid': 365,
 'next': 366,
 'came': 367,
 'getting': 368,
 'women': 369,
 'understand': 370,
 'full': 371,
 'remember': 372,
 'let': 373,
 'school': 374,
 'keep': 375,
 'camera': 376,
 'terrible': 377,
 'others': 378,
 'moments': 379,
 'awful': 380,
 'mean': 381,
 'wonderful': 382,
 'sex': 383,
 'perhaps': 384,
 'playing': 385,
 'itself': 386,
 'video': 387,
 'name': 388,
 'gives': 389,
 'human': 390,
 'often': 391,
 'doing': 392,
 'budget': 393,
 'small': 394,
 'definitely': 395,
 'couldnt': 396,
 'perfect': 397,
 'episode': 398,
 'person': 399,
 'early': 400,
 'top': 401,
 'went': 402,
 'dialogue': 403,
 'absolutely': 404,
 'guys': 405,
 'piece': 406,
 'lines': 407,
 'face': 408,
 'certainly': 409,
 'become': 410,
 'liked': 411,
 'stars': 412,
 'case': 413,
 'sort': 414,
 'head': 415,
 'loved': 416,
 'entire': 417,
 'hope': 418,
 'supposed': 419,
 'felt': 420,
 'lost': 421,
 'several': 422,
 'style': 423,
 'mother': 424,
 'live': 425,
 'entertaining': 426,
 'written': 427,
 'picture': 428,
 'against': 429,
 'finally': 430,
 'laugh': 431,
 'worse': 432,
 'title': 433,
 'waste': 434,
 'problem': 435,
 'friend': 436,
 'boy': 437,
 'sound': 438,
 'beginning': 439,
 'shes': 440,
 'seemed': 441,
 'totally': 442,
 'wanted': 443,
 'based': 444,
 'yes': 445,
 'dark': 446,
 'mr': 447,
 'cinema': 448,
 'care': 449,
 'becomes': 450,
 'fans': 451,
 'humor': 452,
 'lead': 453,
 'already': 454,
 'wont': 455,
 'example': 456,
 'guess': 457,
 'final': 458,
 'youll': 459,
 'called': 460,
 'evil': 461,
 'direction': 462,
 '3': 463,
 'children': 464,
 'lives': 465,
 'able': 466,
 'game': 467,
 'id': 468,
 'turn': 469,
 'throughout': 470,
 'low': 471,
 'drama': 472,
 'wants': 473,
 'white': 474,
 'oh': 475,
 'girls': 476,
 'days': 477,
 'despite': 478,
 'fine': 479,
 '\x96': 480,
 'under': 481,
 'quality': 482,
 'amazing': 483,
 'horrible': 484,
 'theyre': 485,
 'history': 486,
 'writing': 487,
 'works': 488,
 'kill': 489,
 'tries': 490,
 'turns': 491,
 'enjoyed': 492,
 'gave': 493,
 'act': 494,
 'unfortunately': 495,
 'killer': 496,
 'son': 497,
 'michael': 498,
 'side': 499,
 'favorite': 500,
 'past': 501,
 'parts': 502,
 'flick': 503,
 'behind': 504,
 'matter': 505,
 'expect': 506,
 'car': 507,
 'run': 508,
 '1': 509,
 'town': 510,
 'brilliant': 511,
 'eyes': 512,
 'starts': 513,
 'stuff': 514,
 'ones': 515,
 'obviously': 516,
 'myself': 517,
 'sometimes': 518,
 'themselves': 519,
 'says': 520,
 'viewer': 521,
 'killed': 522,
 'took': 523,
 'thinking': 524,
 'soon': 525,
 'directed': 526,
 'group': 527,
 'overall': 528,
 'heart': 529,
 'actress': 530,
 'late': 531,
 'decent': 532,
 'city': 533,
 'art': 534,
 'heard': 535,
 'genre': 536,
 'happens': 537,
 'feeling': 538,
 'kid': 539,
 'highly': 540,
 'hell': 541,
 'fight': 542,
 'child': 543,
 'except': 544,
 'extremely': 545,
 'leave': 546,
 'ill': 547,
 'cannot': 548,
 'wouldnt': 549,
 'close': 550,
 'told': 551,
 'blood': 552,
 'lack': 553,
 'experience': 554,
 'police': 555,
 'hour': 556,
 'moment': 557,
 'coming': 558,
 'etc': 559,
 'looked': 560,
 'wonder': 561,
 'stories': 562,
 'strong': 563,
 'involved': 564,
 'daughter': 565,
 'chance': 566,
 'score': 567,
 'particularly': 568,
 'including': 569,
 'type': 570,
 'hand': 571,
 'attempt': 572,
 'living': 573,
 'save': 574,
 'complete': 575,
 'serious': 576,
 'simple': 577,
 'shown': 578,
 'taken': 579,
 'roles': 580,
 'obvious': 581,
 'god': 582,
 'happened': 583,
 'happen': 584,
 'hilarious': 585,
 'stop': 586,
 'violence': 587,
 'cool': 588,
 'james': 589,
 'across': 590,
 'known': 591,
 'voice': 592,
 'murder': 593,
 'exactly': 594,
 'song': 595,
 'opening': 596,
 'ago': 597,
 'number': 598,
 'robert': 599,
 'usually': 600,
 'released': 601,
 'slow': 602,
 'huge': 603,
 'saying': 604,
 'ok': 605,
 'wish': 606,
 'order': 607,
 'david': 608,
 'cinematography': 609,
 'interest': 610,
 'whose': 611,
 'jokes': 612,
 'hours': 613,
 'reality': 614,
 'english': 615,
 'alone': 616,
 'crap': 617,
 'relationship': 618,
 'sad': 619,
 'lets': 620,
 'hit': 621,
 'running': 622,
 'none': 623,
 'shots': 624,
 'possible': 625,
 'cut': 626,
 'talent': 627,
 'yourself': 628,
 'age': 629,
 'gore': 630,
 'annoying': 631,
 'seriously': 632,
 'career': 633,
 'today': 634,
 'started': 635,
 'call': 636,
 'major': 637,
 'brother': 638,
 'female': 639,
 'taking': 640,
 'usual': 641,
 'please': 642,
 'ends': 643,
 'hero': 644,
 'somewhat': 645,
 'knew': 646,
 'important': 647,
 'view': 648,
 'ridiculous': 649,
 'mostly': 650,
 'documentary': 651,
 'knows': 652,
 'change': 653,
 'beyond': 654,
 'body': 655,
 'finds': 656,
 'turned': 657,
 'opinion': 658,
 'power': 659,
 'words': 660,
 'silly': 661,
 'strange': 662,
 'word': 663,
 'due': 664,
 'novel': 665,
 'upon': 666,
 '5': 667,
 'talking': 668,
 'scary': 669,
 'apparently': 670,
 'anyway': 671,
 'local': 672,
 'attention': 673,
 'directors': 674,
 'husband': 675,
 'happy': 676,
 'clearly': 677,
 'musical': 678,
 'episodes': 679,
 'cheap': 680,
 'four': 681,
 'single': 682,
 'level': 683,
 'problems': 684,
 'arent': 685,
 'room': 686,
 'basically': 687,
 'country': 688,
 '4': 689,
 'disappointed': 690,
 'tells': 691,
 'sequence': 692,
 'british': 693,
 'events': 694,
 'television': 695,
 'modern': 696,
 'miss': 697,
 'talk': 698,
 'light': 699,
 'songs': 700,
 'whats': 701,
 'appears': 702,
 'whether': 703,
 'french': 704,
 'sets': 705,
 'giving': 706,
 'easily': 707,
 'bring': 708,
 'supporting': 709,
 'predictable': 710,
 'havent': 711,
 'add': 712,
 'review': 713,
 'rating': 714,
 'mention': 715,
 'dialog': 716,
 'falls': 717,
 'lots': 718,
 'similar': 719,
 'soundtrack': 720,
 'jack': 721,
 'romantic': 722,
 'needs': 723,
 'team': 724,
 'bunch': 725,
 'george': 726,
 'viewers': 727,
 'above': 728,
 'enjoyable': 729,
 'future': 730,
 'ten': 731,
 'hate': 732,
 'tried': 733,
 'certain': 734,
 'message': 735,
 'moving': 736,
 'five': 737,
 'showing': 738,
 'surprised': 739,
 'within': 740,
 'entertainment': 741,
 'comic': 742,
 'clear': 743,
 'earth': 744,
 'parents': 745,
 'storyline': 746,
 'middle': 747,
 'space': 748,
 'among': 749,
 'filmed': 750,
 'named': 751,
 'fall': 752,
 'dull': 753,
 'theme': 754,
 'easy': 755,
 'theater': 756,
 'king': 757,
 'feels': 758,
 'ways': 759,
 'typical': 760,
 'greatest': 761,
 'kept': 762,
 'release': 763,
 'thriller': 764,
 'using': 765,
 'near': 766,
 'comments': 767,
 'stay': 768,
 'sequel': 769,
 'buy': 770,
 'doubt': 771,
 'gone': 772,
 'working': 773,
 'deal': 774,
 'effort': 775,
 'actual': 776,
 'nearly': 777,
 'monster': 778,
 'writer': 779,
 'elements': 780,
 'sorry': 781,
 'means': 782,
 'tale': 783,
 'fantastic': 784,
 'brought': 785,
 'famous': 786,
 'suspense': 787,
 'subject': 788,
 'die': 789,
 '80s': 790,
 'editing': 791,
 'straight': 792,
 'boys': 793,
 'rock': 794,
 'herself': 795,
 'realistic': 796,
 'imagine': 797,
 'points': 798,
 'feature': 799,
 'sister': 800,
 'general': 801,
 'leads': 802,
 'viewing': 803,
 'lady': 804,
 'move': 805,
 'class': 806,
 'youve': 807,
 'peter': 808,
 'dr': 809,
 'mystery': 810,
 'richard': 811,
 'form': 812,
 'reviews': 813,
 'hear': 814,
 'begins': 815,
 'somehow': 816,
 'material': 817,
 'check': 818,
 'learn': 819,
 'dog': 820,
 'forget': 821,
 'whos': 822,
 'particular': 823,
 'animation': 824,
 'figure': 825,
 'premise': 826,
 'weak': 827,
 'sit': 828,
 'killing': 829,
 'rent': 830,
 'period': 831,
 'believable': 832,
 'expected': 833,
 'surprise': 834,
 'sequences': 835,
 'decided': 836,
 'atmosphere': 837,
 'paul': 838,
 'eventually': 839,
 'crime': 840,
 'deep': 841,
 'difficult': 842,
 'fast': 843,
 'avoid': 844,
 'wait': 845,
 'leaves': 846,
 'red': 847,
 'tom': 848,
 'eye': 849,
 'became': 850,
 'possibly': 851,
 'york': 852,
 'indeed': 853,
 'truth': 854,
 'okay': 855,
 'emotional': 856,
 'follow': 857,
 'situation': 858,
 'average': 859,
 'lame': 860,
 'poorly': 861,
 'forced': 862,
 'dance': 863,
 'meet': 864,
 'needed': 865,
 'stand': 866,
 'footage': 867,
 'shame': 868,
 'begin': 869,
 'scifi': 870,
 'oscar': 871,
 'whatever': 872,
 'crew': 873,
 'open': 874,
 'minute': 875,
 'memorable': 876,
 'features': 877,
 'meets': 878,
 'reading': 879,
 'previous': 880,
 'doctor': 881,
 'whom': 882,
 'season': 883,
 'filmmakers': 884,
 'question': 885,
 'write': 886,
 'sexual': 887,
 'romance': 888,
 'credits': 889,
 'beauty': 890,
 'interested': 891,
 'writers': 892,
 'nor': 893,
 'personal': 894,
 'cheesy': 895,
 'gay': 896,
 'imdb': 897,
 'keeps': 898,
 'third': 899,
 'hot': 900,
 'superb': 901,
 'western': 902,
 'unless': 903,
 'nature': 904,
 'society': 905,
 'inside': 906,
 'total': 907,
 'otherwise': 908,
 'perfectly': 909,
 'towards': 910,
 'hands': 911,
 'male': 912,
 'note': 913,
 'incredibly': 914,
 'sounds': 915,
 'weird': 916,
 'box': 917,
 'de': 918,
 'result': 919,
 'screenplay': 920,
 'japanese': 921,
 'effect': 922,
 'comment': 923,
 'battle': 924,
 'quickly': 925,
 '20': 926,
 'masterpiece': 927,
 'worked': 928,
 'street': 929,
 'realize': 930,
 'plus': 931,
 'laughs': 932,
 'unique': 933,
 'badly': 934,
 'crazy': 935,
 'copy': 936,
 'older': 937,
 'earlier': 938,
 'various': 939,
 'brings': 940,
 'america': 941,
 'appear': 942,
 'background': 943,
 'stage': 944,
 'air': 945,
 'plenty': 946,
 'setting': 947,
 'fairly': 948,
 'island': 949,
 'free': 950,
 'admit': 951,
 'b': 952,
 'lee': 953,
 'powerful': 954,
 'ask': 955,
 'front': 956,
 'portrayed': 957,
 'creepy': 958,
 'business': 959,
 'directing': 960,
 'dramatic': 961,
 'leading': 962,
 'spent': 963,
 'acted': 964,
 'forward': 965,
 'following': 966,
 'joe': 967,
 'rich': 968,
 'remake': 969,
 'development': 970,
 'mark': 971,
 'pay': 972,
 'mess': 973,
 'baby': 974,
 'manages': 975,
 'outside': 976,
 'meant': 977,
 'deserves': 978,
 'dumb': 979,
 'attempts': 980,
 'political': 981,
 'fire': 982,
 '70s': 983,
 'fails': 984,
 'expecting': 985,
 'caught': 986,
 'create': 987,
 'agree': 988,
 'water': 989,
 'ideas': 990,
 'hardly': 991,
 'bill': 992,
 'wasted': 993,
 'fighting': 994,
 'cover': 995,
 'reasons': 996,
 'return': 997,
 'missing': 998,
 'joke': 999,
 'party': 1000,
 ...}

In [22]:
tokenizer.word_counts

OrderedDict([('one', 49980),
             ('of', 285998),
             ('the', 645608),
             ('other', 17640),
             ('reviewers', 491),
             ('has', 32643),
             ('mentioned', 1026),
             ('that', 134776),
             ('after', 14301),
             ('watching', 8825),
             ('just', 34414),
             ('1', 2271),
             ('oz', 252),
             ('episode', 2996),
             ('youll', 2577),
             ('be', 52264),
             ('hooked', 271),
             ('they', 41010),
             ('are', 57730),
             ('right', 6153),
             ('as', 89376),
             ('this', 144281),
             ('is', 208601),
             ('exactly', 1936),
             ('what', 29191),
             ('happened', 1978),
             ('with', 85889),
             ('methe', 86),
             ('first', 16686),
             ('thing', 8821),
             ('struck', 265),
             ('me', 20609),
             ('about', 33598),
             ('was', 94392),
             ('its', 47445),
             ('brutality', 134),
             ('and', 317027),
             ('unflinching', 31),
             ('scenes', 10098),
             ('violence', 1970),
             ('which', 22816),
             ('set', 4335),
             ('in', 181773),
             ('from', 39818),
             ('word', 1747),
             ('go', 9500),
             ('trust', 569),
             ('not', 59018),
             ('a', 316996),
             ('show', 11868),
             ('for', 85490),
             ('faint', 77),
             ('hearted', 127),
             ('or', 34622),
             ('timid', 46),
             ('pulls', 369),
             ('no', 23971),
             ('punches', 120),
             ('regards', 130),
             ('to', 264288),
             ('drugs', 696),
             ('sex', 3133),
             ('hardcore', 248),
             ('classic', 3406),
             ('use', 3497),
             ('wordit', 2),
             ('called', 2572),
             ('nickname', 48),
             ('given', 3480),
             ('oswald', 28),
             ('maximum', 100),
             ('security', 360),
             ('state', 1020),
             ('penitentary', 2),
             ('it', 150085),
             ('focuses', 349),
             ('mainly', 751),
             ('on', 65773),
             ('emerald', 13),
             ('city', 2182),
             ('an', 42308),
             ('experimental', 167),
             ('section', 363),
             ('prison', 881),
             ('where', 12243),
             ('all', 44175),
             ('cells', 95),
             ('have', 54563),
             ('glass', 296),
             ('fronts', 40),
             ('face', 2937),
             ('inwards', 2),
             ('so', 38215),
             ('privacy', 25),
             ('high', 3790),
             ('agenda', 151),
             ('em', 224),
             ('home', 3494),
             ('manyaryans', 1),
             ('muslims', 75),
             ('gangstas', 5),
             ('latinos', 30),
             ('christians', 148),
             ('italians', 83),
             ('irish', 376),
             ('moreso', 25),
             ('scuffles', 2),
             ('death', 3661),
             ('stares', 65),
             ('dodgy', 88),
             ('dealings', 36),
             ('shady', 72),
             ('agreements', 7),
             ('never', 12732),
             ('far', 5679),
             ('awayi', 17),
             ('would', 23803),
             ('say', 10527),
             ('main', 4518),
             ('appeal', 795),
             ('due', 1747),
             ('fact', 6763),
             ('goes', 4677),
             ('shows', 4780),
             ('wouldnt', 2083),
             ('dare', 295),
             ('forget', 1384),
             ('pretty', 7110),
             ('pictures', 826),
             ('painted', 188),
             ('mainstream', 372),
             ('audiences', 983),
             ('charm', 726),
             ('romanceoz', 1),
             ('doesnt', 8794),
             ('mess', 1142),
             ('around', 6937),
             ('i', 144228),
             ('ever', 11537),
             ('saw', 6251),
             ('nasty', 642),
             ('surreal', 426),
             ('couldnt', 3010),
             ('ready', 652),
             ('but', 79676),
             ('watched', 4416),
             ('more', 27406),
             ('developed', 698),
             ('taste', 838),
             ('got', 6858),
             ('accustomed', 56),
             ('levels', 459),
             ('graphic', 458),
             ('injustice', 82),
             ('crooked', 96),
             ('guards', 157),
             ('wholl', 35),
             ('sold', 299),
             ('out', 32446),
             ('nickel', 8),
             ('inmates', 97),
             ('kill', 2389),
             ('order', 1877),
             ('get', 18033),
             ('away', 5233),
             ('well', 18283),
             ('mannered', 59),
             ('middle', 1537),
             ('class', 1422),
             ('being', 12878),
             ('turned', 1770),
             ('into', 17638),
             ('bitches', 19),
             ('their', 22493),
             ('lack', 2071),
             ('street', 1212),
             ('skills', 484),
             ('experience', 2064),
             ('you', 58620),
             ('may', 6483),
             ('become', 2905),
             ('comfortable', 224),
             ('uncomfortable', 257),
             ('viewingthats', 1),
             ('if', 31641),
             ('can', 21643),
             ('touch', 882),
             ('your', 11245),
             ('darker', 205),
             ('side', 2327),
             ('wonderful', 3135),
             ('little', 12197),
             ('production', 3349),
             ('filming', 768),
             ('technique', 295),
             ('very', 27290),
             ('unassuming', 23),
             ('oldtimebbc', 1),
             ('fashion', 616),
             ('gives', 3047),
             ('comforting', 38),
             ('sometimes', 2234),
             ('discomforting', 11),
             ('sense', 4384),
             ('realism', 513),
             ('entire', 2827),
             ('piece', 2940),
             ('actors', 8686),
             ('extremely', 2102),
             ('chosen', 415),
             ('michael', 2332),
             ('sheen', 169),
             ('only', 22812),
             ('polari', 1),
             ('he', 51524),
             ('voices', 423),
             ('down', 6845),
             ('pat', 259),
             ('too', 14643),
             ('truly', 3407),
             ('see', 22225),
             ('seamless', 36),
             ('editing', 1438),
             ('guided', 57),
             ('by', 43614),
             ('references', 547),
             ('williams', 597),
             ('diary', 88),
             ('entries', 103),
             ('worth', 4546),
             ('terrificly', 5),
             ('written', 2774),
             ('performed', 397),
             ('masterful', 184),
             ('great', 17596),
             ('masters', 270),
             ('comedy', 6054),
             ('his', 56880),
             ('life', 11578),
             ('really', 22723),
             ('comes', 4694),
             ('things', 7115),
             ('fantasy', 1017),
             ('guard', 297),
             ('rather', 5207),
             ('than', 19034),
             ('traditional', 448),
             ('dream', 1074),
             ('techniques', 275),
             ('remains', 844),
             ('solid', 932),
             ('then', 15219),
             ('disappears', 151),
             ('plays', 4315),
             ('our', 4914),
             ('knowledge', 547),
             ('senses', 173),
             ('particularly', 2016),
             ('concerning', 233),
             ('orton', 20),
             ('halliwell', 10),
             ('sets', 1613),
             ('flat', 991),
             ('halliwells', 1),
             ('murals', 2),
             ('decorating', 10),
             ('every', 7798),
             ('surface', 414),
             ('terribly', 507),
             ('done', 5803),
             ('thought', 6587),
             ('way', 14865),
             ('spend', 959),
             ('time', 23068),
             ('hot', 1249),
             ('summer', 694),
             ('weekend', 374),
             ('sitting', 886),
             ('air', 1191),
             ('conditioned', 24),
             ('theater', 1511),
             ('lighthearted', 204),
             ('plot', 12212),
             ('simplistic', 204),
             ('dialogue', 2949),
             ('witty', 519),
             ('characters', 14518),
             ('likable', 693),
             ('even', 24076),
             ('bread', 105),
             ('suspected', 105),
             ('serial', 654),
             ('killer', 2345),
             ('while', 9757),
             ('some', 30397),
             ('disappointed', 1679),
             ('when', 27191),
             ('realize', 1212),
             ('match', 1048),
             ('point', 5850),
             ('2', 4102),
             ('risk', 298),
             ('addiction', 148),
             ('proof', 292),
             ('woody', 302),
             ('allen', 468),
             ('still', 10517),
             ('fully', 760),
             ('control', 925),
             ('style', 2795),
             ('many', 13177),
             ('us', 7600),
             ('grown', 405),
             ('lovethis', 11),
             ('most', 16985),
             ('id', 2547),
             ('laughed', 741),
             ('at', 45830),
             ('woodys', 20),
             ('comedies', 805),
             ('years', 8593),
             ('decade', 456),
             ('ive', 6365),
             ('been', 18083),
             ('impressed', 692),
             ('scarlet', 64),
             ('johanson', 5),
             ('she', 23598),
             ('managed', 824),
             ('tone', 857),
             ('her', 33944),
             ('sexy', 855),
             ('image', 733),
             ('jumped', 152),
             ('average', 1310),
             ('spirited', 148),
             ('young', 6874),
             ('womanthis', 2),
             ('crown', 87),
             ('jewel', 146),
             ('career', 1827),
             ('wittier', 8),
             ('devil', 409),
             ('wears', 315),
             ('prada', 13),
             ('interesting', 5970),
             ('superman', 345),
             ('friends', 3616),
             ('basically', 1696),
             ('theres', 5789),
             ('family', 5453),
             ('boy', 2708),
             ('jake', 229),
             ('thinks', 886),
             ('zombie', 1076),
             ('closet', 186),
             ('parents', 1544),
             ('fighting', 1112),
             ('timethis', 37),
             ('movie', 82835),
             ('slower', 79),
             ('soap', 495),
             ('opera', 754),
             ('suddenly', 998),
             ('decides', 1041),
             ('rambo', 120),
             ('zombieok', 1),
             ('youre', 3785),
             ('going', 7964),
             ('make', 15174),
             ('film', 73928),
             ('must', 6118),
             ('decide', 960),
             ('thriller', 1493),
             ('drama', 2531),
             ('watchable', 573),
             ('divorcing', 9),
             ('arguing', 102),
             ('like', 38504),
             ('real', 8935),
             ('we', 18649),
             ('totally', 2680),
             ('ruins', 203),
             ('expected', 1359),
             ('boogeyman', 48),
             ('similar', 1591),
             ('instead', 4104),
             ('meaningless', 218),
             ('spots3', 1),
             ('10', 4140),
             ('playing', 3085),
             ('descent', 171),
             ('dialogs', 262),
             ('shots', 1845),
             ('ignore', 335),
             ('them', 15242),
             ('petter', 1),
             ('matteis', 7),
             ('love', 12448),
             ('money', 4266),
             ('visually', 440),
             ('stunning', 753),
             ('watch', 13304),
             ('mr', 2655),
             ('mattei', 43),
             ('offers', 676),
             ('vivid', 191),
             ('portrait', 264),
             ('human', 3044),
             ('relations', 178),
             ('seems', 7000),
             ('telling', 1079),
             ('power', 1765),
             ('success', 1103),
             ('do', 17544),
             ('people', 17319),
             ('different', 4552),
             ('situations', 944),
             ('encounter', 378),
             ('variation', 96),
             ('arthur', 539),
             ('schnitzlers', 2),
             ('play', 4289),
             ('same', 7931),
             ('theme', 1516),
             ('director', 7237),
             ('transfers', 25),
             ('action', 5873),
             ('present', 1104),
             ('new', 7895),
             ('york', 1317),
             ('these', 10457),
             ('meet', 1301),
             ('connect', 225),
             ('each', 5127),
             ('connected', 263),
             ('another', 8115),
             ('next', 3291),
             ('person', 2990),
             ('know', 12165),
             ('previous', 1273),
             ('contact', 312),
             ('stylishly', 24),
             ('sophisticated', 253),
             ('luxurious', 34),
             ('look', 8016),
             ('taken', 1986),
             ('how', 17153),
             ('live', 2792),
             ('world', 6732),
             ('own', 6445),
             ('habitatthe', 1),
             ('gets', 6202),
             ('souls', 260),
             ('picture', 2757),
             ('stages', 127),
             ('loneliness', 163),
             ('inhabits', 34),
             ('big', 6615),
             ('best', 12215),
             ('place', 4475),
             ('find', 8097),
             ('sincere', 178),
             ('fulfillment', 42),
             ('discerns', 1),
             ('case', 2865),
             ('encounterthe', 2),
             ('acting', 12299),
             ('good', 28282),
             ('under', 2443),
             ('direction', 2568),
             ('steve', 784),
             ('buscemi', 42),
             ('rosario', 53),
             ('dawson', 118),
             ('carol', 217),
             ('kane', 323),
             ('imperioli', 20),
             ('adrian', 94),
             ('grenier', 6),
             ('rest', 3396),
             ('talented', 1084),
             ('cast', 7096),
             ('come', 6091),
             ('alivewe', 1),
             ('wish', 1879),
             ('luck', 453),
             ('await', 45),
             ('anxiously', 24),
             ('work', 7939),
             ('probably', 5494),
             ('my', 23869),
             ('alltime', 218),
             ('favorite', 2323),
             ('story', 21899),
             ('selflessness', 4),
             ('sacrifice', 197),
             ('dedication', 82),
             ('noble', 238),
             ('cause', 1044),
             ('preachy', 135),
             ('boring', 3444),
             ('old', 7698),
             ('despite', 2468),
             ('having', 4746),
             ('seen', 12945),
             ('15', 931),
             ('times', 6032),
             ('last', 5552),
             ('25', 370),
             ('paul', 1345),
             ('lukas', 63),
             ('performance', 5374),
             ('brings', 1196),
             ('tears', 582),
             ('eyes', 2264),
             ('bette', 183),
             ('davis', 497),
             ('few', 7828),
             ('sympathetic', 440),
             ('roles', 1981),
             ('delight', 292),
             ('kids', 3645),
             ('grandma', 81),
             ('says', 2220),
             ('dressedup', 1),
             ('midgets', 22),
             ('children', 2567),
             ('makes', 8233),
             ('fun', 5081),
             ('mothers', 316),
             ('slow', 1895),
             ('awakening', 78),
             ('whats', 1621),
             ('happening', 699),
             ('roof', 149),
             ('believable', 1360),
             ('startling', 118),
             ('had', 21797),
             ('dozen', 344),
             ('thumbs', 226),
             ('theyd', 259),
             ('up', 24030),
             ('sure', 5067),
             ('resurrection', 69),
             ('dated', 481),
             ('seahunt', 2),
             ('series', 5986),
             ('tech', 83),
             ('today', 1826),
             ('bring', 1611),
             ('back', 9117),
             ('kid', 2143),
             ('excitement', 382),
             ('mei', 88),
             ('grew', 462),
             ('black', 3811),
             ('white', 2515),
             ('tv', 5257),
             ('gunsmoke', 20),
             ('were', 21973),
             ('heros', 137),
             ('weekyou', 1),
             ('vote', 477),
             ('comeback', 92),
             ('sea', 600),
             ('huntwe', 1),
             ('need', 3496),
             ('change', 1790),
             ('pace', 1052),
             ('water', 1117),
             ('adventureoh', 1),
             ('thank', 739),
             ('outlet', 34),
             ('view', 1794),
             ('viewpoints', 37),
             ('moviesso', 9),
             ('any', 14824),
             ('ole', 39),
             ('believe', 4871),
             ('wanna', 263),
             ('saywould', 1),
             ('nice', 3712),
             ('read', 3689),
             ('plus', 1210),
             ('points', 1428),
             ('huntif', 1),
             ('rhymes', 38),
             ('lines', 2938),
             ('let', 3225),
             ('submitor', 1),
             ('leave', 2091),
             ('doubt', 1481),
             ('quitif', 1),
             ('lets', 1854),
             ('amazing', 2427),
             ('fresh', 721),
             ('innovative', 201),
             ('idea', 3931),
             ('70s', 1126),
             ('aired', 281),
             ('7', 855),
             ('8', 855),
             ('brilliant', 2268),
             ('dropped', 253),
             ('off', 10770),
             ('1990', 141),
             ('funny', 8224),
             ('anymore', 625),
             ('continued', 229),
             ('decline', 114),
             ('further', 1037),
             ('complete', 1998),
             ('waste', 2725),
             ('todayits', 1),
             ('disgraceful', 35),
             ('fallen', 301),
             ('writing', 2405),
             ('painfully', 411),
             ('bad', 17462),
             ('performances', 3367),
             ('almost', 6119),
             ('mildly', 354),
             ('entertaining', 2779),
             ('respite', 25),
             ('guesthosts', 1),
             ('hard', 4684),
             ('creator', 143),
             ('handselected', 1),
             ('original', 6118),
             ('also', 17360),
             ('chose', 379),
             ('band', 942),
             ('hacks', 49),
             ('followed', 672),
             ('recognize', 403),
             ('such', 9807),
             ('brilliance', 233),
             ('fit', 998),
             ('replace', 153),
             ('mediocrity', 100),
             ('felt', 2820),
             ('give', 6573),
             ('stars', 2886),
             ('respect', 911),
             ('made', 15266),
             ('huge', 1891),
             ('now', 8318),
             ('awful', 3151),
             ('cant', 7407),
             ('encouraged', 75),
             ('positive', 947),
             ('comments', 1490),
             ('here', 9875),
             ('looking', 4535),
             ('forward', 1154),
             ('mistake', 726),
             ('950', 6),
             ('films', 15186),

In [23]:
sequences=tokenizer.texts_to_sequences(df['review'])

In [24]:
from keras.utils import pad_sequences
sequences=pad_sequences(sequences,maxlen=39)

In [25]:
from keras.layers import SimpleRNN,Input,Dense,Embedding,Dropout
from keras.models import Sequential
x=sequences
y=df['sentiment'].values

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [27]:
x_train.shape

(34707, 39)

In [28]:
x_test.shape

(14875, 39)

In [29]:
model = Sequential()
model.add(SimpleRNN(32, input_shape=(39,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5,validation_data=(x_test, y_test),batch_size=64)

WARNING:tensorflow:From c:\Users\mdfaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\mdfaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Epoch 1/5
WARNING:tensorflow:From c:\Users\mdfaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\mdfaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

543/543 [==============================] - 6s 7ms/step - loss: 0.6947 - accuracy: 0.5013 - val_loss: 0.6933 - val_accuracy: 0.5160
Epoch 2/5
543/543 [==============================] - 4s 7ms/step - loss: 0.6943 - accuracy: 0.5024 - val_loss: 0.6934 - val_accuracy: 0.5081
Epoch 3/5
543/543 [==============================] - 3s 6ms/step - loss: 0.6938 - accuracy: 0.5055 - val_loss: 0.6924 - val_accuracy: 0.5161
Epoch 4/5
543/543 [==============================] - 3s 6ms/step - loss: 0.6937 - accuracy: 0.5069 - val_loss: 0.6925 - val_accuracy: 0.5107
Epoch 5/5
543/543 [==============================] - 3s 6ms/step - loss: 0.6936 - accuracy: 0.5050 - val_loss: 0.6925 - val_accuracy: 0.5012

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 simple_rnn (SimpleRNN)      (None, 32)                1088

 dense (Dense)               (None, 1)                 33

=================================================================
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [31]:
vocab_size=len(tokenizer.word_index)+1

In [32]:
from keras.models import Sequential
from keras.layers import Embedding,LSTM, Dense, Dropout
from keras.callbacks import EarlyStopping
from keras.regularizers import l2

final_model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=64, input_length=39, mask_zero=True),
    LSTM(64,dropout=0.2, recurrent_dropout=0.2),
    Dropout(0.5),
    Dense(3, activation='softmax', kernel_regularizer=l2(0.001))
])

final_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

final_model.fit(
    x_train,
    y_train,
    epochs=10,
    validation_data=(x_test, y_test),
    batch_size=64,
    callbacks=[early_stop]
)

Epoch 1/10
543/543 [==============================] - 148s 264ms/step - loss: 0.5551 - accuracy: 0.7097 - val_loss: 0.4625 - val_accuracy: 0.7858
Epoch 2/10
543/543 [==============================] - 135s 249ms/step - loss: 0.4128 - accuracy: 0.8215 - val_loss: 0.4368 - val_accuracy: 0.7980
Epoch 3/10
543/543 [==============================] - 131s 242ms/step - loss: 0.3731 - accuracy: 0.8383 - val_loss: 0.4388 - val_accuracy: 0.7985
Epoch 4/10
543/543 [==============================] - 139s 255ms/step - loss: 0.3412 - accuracy: 0.8537 - val_loss: 0.4883 - val_accuracy: 0.7917

In [33]:
final_model.evaluate(x_test, y_test)

465/465 [==============================] - 3s 7ms/step - loss: 0.4368 - accuracy: 0.7980

[0.4367721974849701, 0.7979831695556641]

In [34]:
y_pred = final_model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

465/465 [==============================] - 3s 6ms/step

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_classes)

array([[6077, 1327],
       [1678, 5793]], dtype=int64)

In [36]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [37]:
final_model.save('model.h5')

c:\Users\mdfaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(